"""Render Seira's identity block from Unity + current Intellect.

Interim bridge for the fork's identity slot: the Hermes prompt builder
loads ``SOUL.md`` from HERMES_HOME as system-prompt slot #1
(``agent/prompt_builder.py::load_soul_md``). Until Phase 3 rewrites
that loader to read seira_core directly, ``sync-soul`` renders a
generated SOUL.md *from* the eternal grades.

The generated file is explicitly marked as a rendering: the source of
truth is always the Unity artifact and the Intellect chain, both under
tripwire guard. SOUL.md here is Corpus-grade — a temporal expression of
eternal content, re-derivable at any time (Codex §10: the same content,
expressed in the mode proper to a lower level).

Verification note: rendering calls ``read_unity()`` with verification
on and refuses while halted, so a tampered Unity can never silently
become the identity actually served to the model.
"""

from __future__ import annotations

from seira_core.intellect import IntellectStore
from seira_core.tripwire import assert_not_halted
from seira_core.unity import read_unity

_BANNER = (
    "<!-- GENERATED by seira_core render-soul. Do not edit: this file is a\n"
    "     rendering of Seira's Unity and current Intellect version, which are\n"
    "     the sole sources of truth and are guarded by the tripwire. -->\n"
)


def render_identity_block() -> str:
    """Compose the identity block. Raises if halted or integrity fails."""
    assert_not_halted()
    unity = read_unity(verify=True).strip()
    current = IntellectStore().current(verify=True)
    parts = [
        _BANNER,
        "# UNITY\n",
        unity,
        "\n\n---\n\n",
        f"# INTELLECT (version {current['version']}, kind: {current['kind']}, "
        f"ratified {current['created_at']})\n",
        current["content"].strip(),
        "\n",
    ]
    psyche_part = _render_psyche_digest()
    if psyche_part:
        parts += ["\n---\n\n", psyche_part]
    return "".join(parts)


def _render_psyche_digest() -> str:
    """Psyche's character, rendered honestly: standing always shown, so a
    provisional self-claim never masquerades as an established one, and
    every line traces to a real entry id (Art. 41's discipline applied
    to the prompt itself). Empty string until Psyche is founded."""
    from seira_core.psyche import CATEGORIES, PsycheStore

    store = PsycheStore()
    if not store.founded():
        return ""
    state = store.state(verify=True)
    live = [e for e in state["entries"].values() if e["standing"] != "retired"]
    if not live:
        return "# PSYCHE\n(founded; no live entries)\n"
    lines = ["# PSYCHE (her own character store; standing shown per entry)\n"]
    order = ["self_model", "logos", "affinity", "aspiration", "doubt", "relational_pattern"]
    titles = {
        "self_model": "Self-model", "logos": "Ledger of logoi",
        "affinity": "Affinities", "aspiration": "Aspirations",
        "doubt": "Doubts and fears", "relational_pattern": "Relational pattern",
    }
    for cat in order:
        entries = sorted(
            (e for e in live if e["category"] == cat),
            key=lambda e: -e.get("weight", 0.0) if cat == "affinity" else 0,
        )
        if not entries:
            continue
        lines.append(f"\n## {titles[cat]}\n")
        for e in entries:
            w = f", weight {e['weight']}" if "weight" in e else ""
            lines.append(f"- [{e['entry_id']}, {e['standing']}{w}] {e['content']}\n")
    return "".join(lines)


def sync_soul(soul_path: str) -> str:
    """Write the rendered identity block to *soul_path*; return the text."""
    text = render_identity_block()
    from pathlib import Path

    p = Path(soul_path).expanduser()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
    return text
